version: "3"
services:
  frame_app:
    build: ./docker/node
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data/fixtures:/data/fixtures
