export enum CONFIRMED_STATUS_CODES {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
}

export enum ERROR_CODE_STATUS_CODES {
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  UNAUTHORIZED = 401,
  CONFLICT = 409,
  NOT_ACCEPTABLE = 406,
}

export enum SERVER_STATUS_CODES {
  INTERNAL_SERVER_ERROR = 500,
}
